// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjkOM7ZE8X7A3kZGW9Tan7QU6-73psxdQ',
    appId: '1:614555758902:android:ee6600e49c3710ced84397', // Placeholder, ganti dengan appId web dari Firebase Console
    messagingSenderId: '614555758902',
    projectId: 'try-not-to-smile-d3e6a',
    authDomain: 'try-not-to-smile-d3e6a.firebaseapp.com',
    storageBucket: 'try-not-to-smile-d3e6a.firebasestorage.app',
    measurementId: null, // Add if using Analytics
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjkOM7ZE8X7A3kZGW9Tan7QU6-73psxdQ',
    appId: '1:614555758902:android:ee6600e49c3710ced84397',
    messagingSenderId: '614555758902',
    projectId: 'try-not-to-smile-d3e6a',
    storageBucket: 'try-not-to-smile-d3e6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjkOM7ZE8X7A3kZGW9Tan7QU6-73psxdQ',
    appId: '1:614555758902:ios:ee6600e49c3710ced84397', // Placeholder
    messagingSenderId: '614555758902',
    projectId: 'try-not-to-smile-d3e6a',
    storageBucket: 'try-not-to-smile-d3e6a.firebasestorage.app',
    iosBundleId: 'com.tasmile.tryNotToSmile', // Placeholder
  );
}